### ISSUE TITLE
[BUG] cannot compile on ubuntu 15.04 // ウブンチュ１５.04でコンパイルできません。

### ISSUE THREAD

**Issue by nieknooijens** [zakki/openhsp#1]
Hi there
今日は

I'm trying to get the HSP3 working on linux, the hspcmp works, but the runtime itself doesn't compile:
今HSP3をコンパイルしてみますが「hspcmp」は動いていますがランタイムをコンパイルできませんでした。

niek@niek-XNB:~/Bureaublad/openhsp/hsp3$ make linux //CLANG
clang -Wall -DHSPLINUX  -DHSPDEBUG -c hsp3int.cpp -o hsp3int.o
hsp3int.cpp:427:30: warning: unsequenced modification and access to 't'
      [-Wunsequenced]
                return ease_diff*(7.5625*(t-=(1.5/2.75))*t + .75);
                                           ^             ~
hsp3int.cpp:429:30: warning: unsequenced modification and access to 't'
      [-Wunsequenced]
                return ease_diff*(7.5625*(t-=(2.25/2.75))*t + .9375);
                                           ^              ~
hsp3int.cpp:431:30: warning: unsequenced modification and access to 't'
      [-Wunsequenced]
                return ease_diff*(7.5625*(t-=(2.625/2.75))*t + .984375);
                                           ^               ~
hsp3int.cpp:1221:3: error: use of undeclared identifier 'ReplaceSetMatch'
                ReplaceSetMatch( s_buffer, ss );
                ^
hsp3int.cpp:1224:14: error: use of undeclared identifier 'ReplaceStr'
                s_result = ReplaceStr( s_rep );
                           ^
hsp3int.cpp:1226:15: error: use of undeclared identifier 'ReplaceDone'
                ctx->stat = ReplaceDone();
                            ^
3 warnings and 3 errors generated.
makefile:329: recept voor doel 'hsp3int.o' is mislukt
make: *** [hsp3int.o] Fout 1
niek@niek-XNB:~/Bureaublad/openhsp/hsp3$ make linux //GCC
gcc -Wall -finput-charset=cp932 -fexec-charset=cp932 -DHSPLINUX  -DHSPDEBUG -c hsp3int.cpp -o hsp3int.o
hsp3int.cpp: In function ‘double _ease_bounce(double)’:
hsp3int.cpp:427:51: warning: operation on ‘t’ may be undefined [-Wsequence-point]
   return ease_diff*(7.5625*(t-=(1.5/2.75))*t + .75);
                                                   ^
hsp3int.cpp:429:54: warning: operation on ‘t’ may be undefined [-Wsequence-point]
   return ease_diff*(7.5625*(t-=(2.25/2.75))*t + .9375);
                                                      ^
hsp3int.cpp:431:57: warning: operation on ‘t’ may be undefined [-Wsequence-point]
   return ease_diff*(7.5625*(t-=(2.625/2.75))*t + .984375);
                                                         ^
hsp3int.cpp: In function ‘int cmdfunc_intcmd(int)’:
hsp3int.cpp:1221:33: error: ‘ReplaceSetMatch’ was not declared in this scope
   ReplaceSetMatch( s_buffer, ss );
                                 ^
hsp3int.cpp:1224:32: error: ‘ReplaceStr’ was not declared in this scope
   s_result = ReplaceStr( s_rep );
                                ^
hsp3int.cpp:1226:27: error: ‘ReplaceDone’ was not declared in this scope
   ctx->stat = ReplaceDone();
                           ^
hsp3int.cpp: At global scope:
hsp3int.cpp:56:12: warning: ‘qsort_order’ defined but not used [-Wunused-variable]
 static int qsort_order;
            ^
hsp3int.cpp:103:13: warning: ‘void QuickSort(DATA*, int, int)’ defined but not used [-Wunused-function]
 static void QuickSort( DATA *data, int nmem, int asdes )
             ^
hsp3int.cpp:245:13: warning: ‘void StrToData(char*, int, int, DATA*)’ defined but not used [-Wunused-function]
 static void StrToData( char *adr, int num, int len, DATA *data )
             ^
hsp3int.cpp:258:13: warning: ‘void DataToStr(DATA*, char*, int, int)’ defined but not used [-Wunused-function]
 static void DataToStr( DATA *data, char *adr, int num, int len )
             ^
hsp3int.cpp:309:13: warning: ‘void DataInc(int)’ defined but not used [-Wunused-function]
 static void DataInc( int n )
             ^
makefile:329: recept voor doel 'hsp3int.o' is mislukt
make: *** [hsp3int.o] Fout 1

**Comment by zakki** [comment]
This repository is mirror of http://dev.onionsoft.net/trac/openhsp/ to publish my experimental branches.
このリポジトリはOpenHSPでの実験的な機能のため複製です。

I work mainly on hsp3dish.js and hsp3ll, so see HSP bug tracker (or onion software blog) about HSPLINUX.
私は主にhsp3dish.jsやllvm版を担当しているたも、他の部分のバグ報告はHSPのBTSにお願いします。
http://dev.onionsoft.net/mantis/my_view_page.php
http://www.onionsoft.net/wp/archives/1486

FYI
Current officially maintained platforms are listed below. As far as I know, HSPLINUX has no maintainer now.
現在、メンテナンスされているプラットフォームは以下のとおりです。
hsp3gui, hsp3cl: Windows
hsp3dish: Windows, Android, iOS, Emscripten

If you just want to try HSP lang, hsp3dish.js or hsproom may be run on Linux.
http://hsproom.me/

If you are interested in OpenHSP develop, please consider to join the hsp-dev mailing list.
もしOpenHSP自体の開発に興味があればhsp-dev MLへの参加をおすすめします。
http://ml.x1jp.com/hsp-dev/
